// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8miM_QrqQFArHEPwU4BuH2cDOV7wXY1E',
    appId: '1:164313311350:web:a52484fb2eae000c869757',
    messagingSenderId: '164313311350',
    projectId: 'agri-c6980',
    authDomain: 'agri-c6980.firebaseapp.com',
    storageBucket: 'agri-c6980.appspot.com',
    measurementId: 'G-7CM05DH73Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN53RLEDCwom6GZ_6EcNNOaym5lYW7u7k',
    appId: '1:164313311350:android:c0dc5433754d8a97869757',
    messagingSenderId: '164313311350',
    projectId: 'agri-c6980',
    storageBucket: 'agri-c6980.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq-1ilu3brEF5g1ie9p_Axp8I5PJX-WrY',
    appId: '1:164313311350:ios:c2f19f6620f57629869757',
    messagingSenderId: '164313311350',
    projectId: 'agri-c6980',
    storageBucket: 'agri-c6980.appspot.com',
    iosBundleId: 'com.example.bhyapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCq-1ilu3brEF5g1ie9p_Axp8I5PJX-WrY',
    appId: '1:164313311350:ios:0cc05145fa881b7c869757',
    messagingSenderId: '164313311350',
    projectId: 'agri-c6980',
    storageBucket: 'agri-c6980.appspot.com',
    iosBundleId: 'com.example.bhyapp.RunnerTests',
  );
}
